replicaCount: 1
frontend:
  image:
    repository: aksacrmicoservices.azurecr.io/crud-app-frontend
    tag: "25560603408"
backend:
  image:
    repository: aksacrmicoservices.azurecr.io/crud-app-backend
    tag: "25560893626"
